name: Tomer Testings

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch name to test'
        required: False

jobs:
  S1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 8
        format: 'YYYY-MM-DD-HH-mm-ss'
    - name: Tomer_placeholder
      run: echo "Hello world_7 " $TIME
